### ISSUE TITLE
Count on documents greater than 1 Million

### ISSUE THREAD

**Issue by craigderington** [huggingface/Mongoku#13]
The Mongoku UI displays values, such as counts on total documents in a collection greater than 1 million as 1000,000.

**Comment by n1t0** [comment]
Can you give me more precision about this? What do you expect, what is happening instead, ...

Here is what I have on collections with 1+ million of objects, and it seems totally fine to me:
<img width="250" alt="Screen Shot 2019-04-18 at 5 31 12 PM" src="https://user-images.githubusercontent.com/1217986/56392624-e818b980-61ff-11e9-80ee-4af812134285.png">

**Comment by craigderington** [comment]
Strange.  My Mongoku UI looks like this when count is > 1 M.

![Screenshot 2019-04-19 09 47 21](https://user-images.githubusercontent.com/1760686/56427003-50ab7900-6288-11e9-86d7-c3fc82be06e0.png)

![Screenshot 2019-04-19 09 47 39](https://user-images.githubusercontent.com/1760686/56427008-53a66980-6288-11e9-8324-8c1ce44efa6c.png)

Thanks!

**Comment by craigderington** [comment]
Closed.
