### ISSUE TITLE
Showing count of results

### ISSUE THREAD

**Issue by molie94** [huggingface/Mongoku#15]
It seems that we cannot see the count of the result when we do a query.
The total number of document does not change and this seems to be a bug to me.
Is there a way to show the count of the results only for the queries?
For example the result of the query of the following does not change the 1 - 20 of $TOTAL Documents.
$TOTAL seems to be the same no matter what the query is.

db.getCollection('events').find({
    timestamp: {
        $gte: ISODate("2017-10-13T03:00:00.993Z"),
        $lt: ISODate("2017-10-14T16:59:09.993Z")
    }
}).count()

**Comment by lampapetrol** [comment]
I submitted a potential fix : https://github.com/huggingface/Mongoku/pull/19

**Comment by n1t0** [comment]
This has been fixed in the last release
