### ISSUE TITLE
not work on http://localhost:27017/

### ISSUE THREAD

**Issue by cnscorpions** [huggingface/Mongoku#31]
1. install on docker as readme writes
2. navigate to http://localhost:27017/
3. it shows that It looks like you are trying to access MongoDB over HTTP on the native driver port.
4. just search around, and seems that mongodb 3.6 + remove http interface, 
:(

**Comment by opsct** [comment]
Try with **http://localhost:3100/** instead.

MONGOKU_DEFAULT_HOST defines the mongo servers preconfigured at startup, not the address of mongoku.

**Comment by cnscorpions** [comment]
all right, I turn to mongodb compass now, not web gui. so close this issue.
